-- Medien-Tabelle (MIT Großbuchstaben!)
DROP TABLE IF EXISTS mediums;
CREATE TABLE mediums (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Autor VARCHAR(255) NOT NULL,
    Standort VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Backup-Tabelle
DROP TABLE IF EXISTS backup;
CREATE TABLE backup (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Autor VARCHAR(255) NOT NULL,
    Standort VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;